// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idqjeszptaejghuzalvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcWplc3pwdGFlamdodXphbHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODU0NjcsImV4cCI6MjA3NDE2MTQ2N30.hQCta55c0EeqZsx5GsXAbxHmERDy1BNZza3PiT2CFfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});